### ISSUE TITLE
Problem with instalation 

### ISSUE THREAD

**Issue by alfonsoopazom** [pablovin/ChefsHatGYM#10]
Hi, i have a problem with the intalation process in my conda virtual env. When i run command "pip install chefshatgym", the command line show up this error:

![Captura de Pantalla 2021-05-17 a la(s) 10 11 41](https://user-images.githubusercontent.com/30917026/118503091-4de61100-b6f8-11eb-8ace-8868eec036c2.png)

Can anyone help me please ? 

the laptop im use is a mackbook pro mid 2012.

**Comment by pablovin** [comment]
Hi!

I think we solved, right?

I updated the dependencies list, and if you having trouble, try to install the latest version from pip:https://pypi.org/project/ChefsHatGym/
